### ISSUE TITLE
Amplitude client using ForkJoinPool for I/O

### ISSUE THREAD

**Issue by kevink-sq** [amplitude/Amplitude-Java#108]
## Expected Behavior
sendEvents should use `sendThreadPool` instead of the default `ForkJoinPool`.

## Current Behavior
sendEvents uses the default `ForkJoinPool` via `CompletableFuture.supplyAsync(runnable)` which scales with the number of cpu.

## Possible Solution
See https://github.com/amplitude/Amplitude-Java/pull/107

**Comment by kevink-sq** [comment]
cc: @izaaz

**Comment by izaaz** [comment]
@kevink-sq this should be released now. Thank you for making the change in the repo and testing this out!
