### ISSUE TITLE
Event.sessionId can't be set to System.currentTimeMillis()

### ISSUE THREAD

**Issue by richard-bio** [amplitude/Amplitude-Java#17]
## Expected Behavior
I expect to be able to set `event.sessionId` to `System.currentTimeMillis()`

## Current Behavior
`event.essionId` is type `int` so the above results in a compile error

## Possible Solution
Change `event.sessionId` to `long`? (which appears to be the case in the other Amplitude SDKs)

## Steps to Reproduce
1. Try to compile `event.sessionId = System.currentTimeMillis();`

## Environment
- Amplitude Java SDK 1.2.0, Java Version 11.0.6+10 (64 bit)
- Device: Mac Book Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
- OS: macOS 11.2.3

**Comment by dantetam** [comment]
Good catch, @richard-bio . We're working on a fix very soon. Will close when the new version is released

**Comment by dantetam** [comment]
This issue is fixed in the newest version of the Java SDK released just now, v1.2.1. Thank you again for the good reporting.
