### ISSUE TITLE
SDK did not exception when wrong apikey, also do you have the way to enable log when using sdk ? 

### ISSUE THREAD

**Issue by TuanDang1509** [amplitude/Amplitude-Java#20]
Using wrong api-key but sdk without thow or log any exception.
![image](https://user-images.githubusercontent.com/40897284/122873890-8a8ed300-d35c-11eb-998a-19c60c99489c.png)

## Expected Behavior
Should throw out clearly exception about wrong credentials.

## Current Behavior
Just keep silent in case wrong key.

## Possible Solution
Should throw out clearly exception about wrong credentials.
Should not retry hundred times in case wrong key.

You should response response.status = 401 in this case and throw out if meet this err code.

## Environment
- Unity Plugin Version: 
- Device: 
- Device OS and Version:

**Comment by TuanDang1509** [comment]
Please update your document about sdk version. Cause the version below was fail when build with jdk 11

![image](https://user-images.githubusercontent.com/40897284/122518811-e47d5900-d03b-11eb-96ff-1e31b9b18f37.png)

**Comment by dantetam** [comment]
Good catch on the Java version issue @TuanDang1509 . That's been fixed now.

That's also good reporting for the wrong API key case. We'll improve on that.

**Comment by TuanDang1509** [comment]
Hi @dantetam ,
Thank you for quickly response on this. I have just take a look at sdk source code.
Could you please consider change apiKey parameter from String to char[] ? 
Cause I am using char[] to store key as below advice. I can change to String when call Amplitude but I think it's better if char[] is used.
https://www.baeldung.com/java-storing-passwords


![image](https://user-images.githubusercontent.com/40897284/122526346-63768f80-d044-11eb-8fe1-660e32f346a9.png)

**Comment by yuhao900914** [comment]
@TuanDang1509 
1. For the suggestion of using char[] for apiKey:
    I just looked over the link you provided. I think the apiKey is not meant to be a secure password and actually, we don't need to change it so it's ok to immutable. Also from a convention perspective, we want to keep using the String type for apiKey. 
2. For the requirement of making the private method public. 
   Actually, we don't want to the public those private functions to the customer. And we are going to add unit tests in this sprint. But you're welcome to write your own tests inside the SDK.

**Comment by TuanDang1509** [comment]
Thank you @yuhao900914,

I got your point of view.

**Comment by yuhao900914** [comment]
Hi @TuanDang1509, 
We fixed the API key issue in the new version v1.2.2. It will be released soon. 
The response status will be still 400 since that's not an easy change for the HTTP API side. And because we are using async call, it cannot directly throw exceptions without joining the main thread. 
However, for the API key issue, we are able to print out the error message with the logger.  And it also won't retry anymore.
Thanks.
