### ISSUE TITLE
Unwanted properties like $price, $quantity and $revenue are set to ZERO while setting the user properties by Java-SDK.

### ISSUE THREAD

**Issue by mananshah88** [amplitude/Amplitude-Java#29]
Hello, 
In my project, I need to log the "user properties" of a specific user.

I am using following dependency: 
`compile group: 'com.amplitude', name: 'java-sdk', version: '1.2.3'`

Here, is what my code looks like:
```

Amplitude client = Amplitude.getInstance();
client.init("PROJECT_API_KEY");

Event event = new Event("registerd_from_channel", "USER'S EMAILID");

JSONObject userProps = new JSONObject();
	try {
		userProps.put("is_user_registerd_from_channel", true);
	} catch (JSONException e) {
		error("Invalid JSON");
		e.printStackTrace();
	}

event.userProperties = userProps;
client.logEvent(event);

```

Problem: 
This code exactly worked as per the expectation but with this, some additional unwanted properties are also logged. like 
```
$price -> 0
$quantity -> 0
$revenue -> 0
```

Question:
How can I avoid such unwanted properties?

Sorry, I am a newbie in Amplitude and I have followed the following document: `https://developers.amplitude.com/docs/java`

It would be great if someone can suggest any blog/document for this.

Thanks in Advance
Manan

**Comment by yuhao900914** [comment]
Thanks for giving us valuable feedback. Want to give you an update that we already planned to work on that. Will give you another update after that is done.

**Comment by mananshah88** [comment]
Ok. Thanks for the Response.

One more question: 
I am ready to downgrade the Amplitude version till the time. 
Can any lower version has supported this?

**Comment by qingzhuozhen** [comment]
Hi @mananshah88 We already fixed the issue for revenue. Please update to newer version to fix this. For lower version it might have the same issue.
