### ISSUE TITLE
Add ability to override default value of "user_id" length

### ISSUE THREAD

**Issue by korzunv** [amplitude/Amplitude-Java#40]
Hello,
In my project there are some cases where I need to use 'user_id' shorter than 5 symbols. API has ability to override the default value of 5 by sending additional field "options", it will be really great to have such ability in SDK.

Thanks in advance.

**Comment by hanangi** [comment]
Is there an estimation for this fix?
Thanks.

**Comment by hanangi** [comment]
added a pull request which address this issue: https://github.com/amplitude/Amplitude-Java/pull/43

**Comment by hanangi** [comment]
V1.5 is out with options support.
When it will be in Maven respository?

**Comment by justin-fiedler** [comment]
1.5 is available now:
https://search.maven.org/artifact/com.amplitude/java-sdk/1.5.0/jar
