### ISSUE TITLE
Why are all Event class attributes public?

### ISSUE THREAD

**Issue by joarobles** [amplitude/Amplitude-Java#58]
## Why are all Event class attributes public?
It seems weird to have assignations like this since other classes in the same package make use of `setter` methods:

```java
event.eventProperties = eventProps;
```

**Comment by bohan-amplitude** [comment]
Hi @joarobles ,

Thank you for submitting question here. The event class was designed like this and released for a long time. Changing to setter/getter may cause customer modifying their integration. We are working on a new version of JVM SDK written in Kotlin. The new SDK will be well designed and organized with high quality. In the meantime we'll continue maintain this Java SDK 's functionality.
