### ISSUE TITLE
Incompatible class type version 59 with JDK 8

### ISSUE THREAD

**Issue by bhadkenaresh841** [amplitude/Amplitude-Java#6]
Unable to use amplitude java SDK on JDK 1.8 as Amplitude 1.0.1 is compiled on JDK 16, Throwing runtime exception class file has wrong version 59.0, should be 52.0.

**Comment by dantetam** [comment]
Hello @bhadkenaresh841 ,

My apologies. I'm currently resolving the issue right now. This library should be compiled with Java 1.8.

Dante

**Comment by dantetam** [comment]
Hello @bhadkenaresh841 , this should be fixed in version 1.1.0 of the Java SDK.

**Comment by bhadkenaresh841** [comment]
@dantetam Thank you for the quick resolution.
