### ISSUE TITLE
Generated Ampli class doesn't compile

### ISSUE THREAD

**Issue by dmoidl** [amplitude/Amplitude-Java#60]
Hi Ampli team 👋 

I'm trying to [migrate](https://developers.data.amplitude.com/jre-ampli#migrating-from-an-itly-jre-runtime) our Kotlin code using the (now deprecated) Itly SDK to Ampli SDK. However, there's an issue preventing me from doing so.

## Expected Behavior
The generated Kotlin file `Ampli.kt` compiles.

## Current Behavior
The generated Kotlin file `Ampli.kt` _does not_ compile.

## Possible Solution
As we don't send any `Identify` events from our code at all, a workaround is to simply remove the whole `identify` method from the generated code. It should be apparent why we're not OK with that 🙂

## Steps to Reproduce
1. Switch the `Runtime` of corresponding `Source` from `JRE - Java (Itly)` (the deprecated one) to `JRE - Kotlin` in Amplitude's UI and save.
![Screenshot 2022-03-18 at 20 00 23](https://user-images.githubusercontent.com/52403892/159007936-35fe84a2-8077-489b-b633-b8de0b35a763.png)
⬇️ 
![Screenshot 2022-03-18 at 20 03 33](https://user-images.githubusercontent.com/52403892/159007946-bf10612f-617f-4df4-a6c4-6518d43e92ae.png)
2. Run `ampli pull <source>`
3. Try to compile the project
4. Observe that the project doesn't compile because the generated `Ampli.kt` file (see the file that gets generated for us [here](https://github.com/amplitude/Amplitude-Java/files/8304719/Ampli.kt.txt)) contains an unresolved reference (line 121 of the attached file)

The problem seem to be with the `Identify` class that is not generated within the file itself nor is it imported, hence doesn't get resolved.

## Environment
MacOs, `ampli` installed via `brew`.
Ampli CLI version: `@amplitude/ampli/1.4.0 darwin-x64 node-v12.22.10`

## Others
Apologies if this is not the correct place to report the issue, but I couldn't find any repository related to the CLI itself and it does directly relate to the JVM SDK as well.

**Comment by justin-fiedler** [comment]
Hi @dmoidl, thanks for submitting this issue. We are looking into the problem and will get back you soon.

**Comment by justin-fiedler** [comment]
We have located the cause and are working on a fix. I will update the post when it is ready, hopefully early next week. Thanks!

**Comment by justin-fiedler** [comment]
Hi @dmoidl we deployed a patch to production that should resolve the issue. Let me know how it goes. Thanks!

**Comment by dmoidl** [comment]
Hi @justin-fiedler. I'm happy to report that the new version of Ampli CLI generates code that does compile 😉  Thanks for a prompt fix!
