### ISSUE TITLE
Events are taking long time to appear in Amplitude

### ISSUE THREAD

**Issue by carlosRetorna** [amplitude/Amplitude-Java#68]
Hello! I'm currently integrating my AWS platform with amplitude to log some backend events.

The events are logged successfully, the SDK does not throw any exception, the events sometimes take 30+ minutes to show inside the Amplitude console. Sometimes the event does not even arrive to amplitude.

Here is my amplitude initialisation:
`amplitude = Amplitude.getInstance();`
`amplitude.init(System.getenv("AMPLITUDE_API_KEY"));`
`amplitude.useBatchMode(false);`
`amplitude.setLogMode(AmplitudeLog.LogMode.WARN);`
`amplitude.setEventUploadThreshold(1);`
`amplitude.setEventUploadPeriodMillis(1000);`

**Comment by bohan-amplitude** [comment]
Hi @carlosRetorna ,

Thank you for the feedback. I'll help investigate the issue. Can you share more detailed info? Code example of log events, aws service used, setting the log level to "debug" to see more information and a link to dashboard that shown the delayed events could be helpful.

**Comment by Fenix0904** [comment]
Hi, I have the same issue. I send about 100 events and some events are visible in an Amplitude and some are not (e.g. my `first_result` event)

**Comment by Fenix0904** [comment]
@bohan-amplitude, can you help?
