### ISSUE TITLE
Invalid API Key: java.lang.NullPointerException

### ISSUE THREAD

**Issue by neee** [amplitude/Amplitude-Java#69]
## Invalid API Key: java.lang.NullPointerException in the logs

I set up the java client:
```
    @Bean
    fun amplitudeClient(): Amplitude =
        Amplitude.getInstance()
            .apply {
                this.init(apiKey)
                this.setOptions(Options().apply { minIdLength = 1 })
                this.useBatchMode(true)
                this.setEventUploadThreshold(1_000)
                this.setEventUploadPeriodMillis(5_000)
            }
```
but part of requests returns an error: `Invalid API Key: java.lang.NullPointerException` looks like on Amplitude side the error is wrapped, maybe you can check your logs and give me more information about the error?

I checked the requests and sure that key is present and valid.

**Comment by yuhao900914** [comment]
cc: @bohan-amplitude

**Comment by bohan-amplitude** [comment]
@neee Thanks for the feedback. I'll look into this.

**Comment by neee** [comment]
@bohan-amplitude any updates? I also created a support request, I think if you need details, just contact me (it is production problem)

**Comment by neee** [comment]
@bohan-amplitude do you need some info, or you think that problem on my side?
Maybe you can give contact to investigate the problem, I can't find the rules how to reproduce the issue.

**Comment by bohan-amplitude** [comment]
@neee Please check the new v1.9.1
