### ISSUE TITLE
SDK Version 1.0.1 build fail with JDK 11. 

### ISSUE THREAD

**Issue by TuanDang1509** [amplitude/Amplitude-Java#9]
## Expected Behavior

Run gradlew build successful with jdk 11

## Current Behavior

Run build failed

## Possible Solution

Using version 1.0.0 as temporary resolve this

implementation 'com.amplitude:java-sdk:1.0.0'

## Steps to Reproduce
 

1.  update build.grade 
 sourceCompatibility = '11'
 targetCompatibility = '11'
...
implementation 'com.amplitude:java-sdk:1.0.1'
2. Run .\gradlew clean build 
3.

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.amplitude:java-sdk:1.0.1.
     Required by:
         project :
      > No matching variant of com.amplitude:java-sdk:1.0.1 was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.amplitude:java-sdk:1.0.1 declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 15 and the consumer needed a component compatible with Java 11
          - Variant 'javadocElements' capability com.amplitude:java-sdk:1.0.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability com.amplitude:java-sdk:1.0.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 15 and the consumer needed a component compatible with Java 11
          - Variant 'sourcesElements' capability com.amplitude:java-sdk:1.0.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
## Environment
- Unity Plugin Version: 
- Device: 
- Device OS and Version:

**Comment by dantetam** [comment]
Sorry, @TuanDang1509 , please try again with Java SDK 1.1.0. This issue should be fixed.
#7

**Comment by dantetam** [comment]
I released on Maven, instead of GitHub.
