### ISSUE TITLE
How to log revenue through Java SDK?

### ISSUE THREAD

**Issue by neokim** [amplitude/Amplitude-Java#92]
Hi, I'd like to log revenue from server side. But the combination of Java SDK and Ampli Codegen doesn't seem to have any APIs related to revenue logging.

`com.amplitude.Event` class has `revenue` field. It seems like would be used automatically for revenue tracking and LTV calculation, etc. But through Ampli, I cannot access the field in any way.

Is there any other way to log revenue that I'm missing?

**Comment by justin-fiedler** [comment]
HI @neokim, thanks for choosing Amplitude. 

You are correct that currently there is no straight forward way to access the revenue values for Ampli events. In most of our newer SDKs we provide access to all Event fields except for `eventType` and `eventProperties` via `EventOptions` that can be passed to `track(event, eventOptions)`.

Unfortunately the Java SDK only exposes a small number of properties and will need to be updated to allow setting revenue (among other fields).

I added this ticket to the backlog to add support for the additional fields.

**Comment by neokim** [comment]
Thank you for the response. I look forward to the update.

**Comment by justin-fiedler** [comment]
Hi @neokim we just merged updates to Ampli Java codegen to include all Event properties on EventOptions.

It should be released in the next couple days. I will follow up after it's in production.

**Comment by justin-fiedler** [comment]
Hi @neokim, EventOptions has been updated to include revenue related properties. You can use these for revenue tracking via Ampli.

e.g. (Koltin used for conciseness)

```kotlin
track(MyEvent(), EventOptions(price = 1.99, quality = 1))
```
