### ISSUE TITLE
Extend the possibility to override AmplitudeLog logic

### ISSUE THREAD

**Issue by alok1111** [amplitude/Amplitude-Java#93]
## Summary
I'd like Amplitude to use my system logger. Current `AmplitudeLog` and `LogMode` implementations don't allow me to reuse the logic from `com.amplitude.AmplitudeLog#log` method.
Sample implementation:
```
    private class AmplitudeLogWrapper extends AmplitudeLog {
        @Override
        public void log(String tag, String message, LogMode messageMode) {
            if (messageMode.level >= logMode.level) {
                if (messageMode.level >= LogMode.ERROR.level) {
                    log.error(tag + ": " + message);
                } else {
                    log.info(tag + ": " + message);
                }
            }
        }
    }
```
`com.amplitude.AmplitudeLog#logMode` and `com.amplitude.AmplitudeLog.LogMode#level` fields are inaccessible due to `AmplitudeLog` and `LogMode` implementations.
Please add corresponding getters as we can only use reflection to get the values.

## Motivations
More friendly API that doesn't force you to use reflection.

**Comment by yuhao900914** [comment]
Thanks for choosing amplitude. We appreciate your feedback. 
The new version has the support to access logMode and logLevel. Please check it out. 
Thanks.
