### ISSUE TITLE
How to use Identify API in Java?

### ISSUE THREAD

**Issue by alok1111** [amplitude/Amplitude-Java#96]
## Summary

Hi Team, I don't see any mentions of the [Identify API](https://www.docs.developers.amplitude.com/analytics/apis/identify-api/) in the [docs](https://www.docs.developers.amplitude.com/data/sdks/java/) and source code.

But looks like it works if I send events like this:
```
        var event = new Event(eventName, userId);
        event.userProperties = new JSONObject(Map.of("$postInsert", appendableUserPropertiesMap));
        amplitude.logEvent(event);
```
Could you please confirm that the Identify API is officially supported for the events from Java SDK?

**Comment by Mercy811** [comment]
Hi, @alok1111, here is no identify API in Java SDK, but an equivalent of `$set` is setting [user properties directly](https://www.docs.developers.amplitude.com/data/sdks/java/#set-user-properties). For other operations, you can follow the structure:

```
// Event() structure 
{
   userProperties: {
       {operator}: {
            key: value
        }
   }
}
```

In your case, it should be 
```
var event = new Event(eventName, userId);
event.userProperties = new JSONObject(Map.of("$set", appendableUserPropertiesMap));
// or you can directly call
//event.userProperties = new JSONObject(appendableUserPropertiesMap);
amplitude.logEvent(event);
```

We will update the docs to better describe this.
